/**
 * Pacing / tension analytics client — fetches a per-beat tension curve plus
 * code-derived pacing insights from FastAPI (POST /analytics/tension).
 *
 * The model supplies only the per-beat tension numbers (in the order the
 * backend hands it); the structural judgment (climax placement, flat stretches,
 * overall shape) is computed in application code on the backend. This client
 * just renders what the backend returns.
 */

export type PacingTag = "quiet" | "slow" | "building" | "peak" | "falling";

export interface TensionBeat {
  title: string;
  tension: number; // 1..10
  pacing: PacingTag;
  note: string;
}

export interface Peak {
  index: number;
  title: string;
  tension: number;
}

export interface FlatStretch {
  start_index: number;
  length: number;
  beat_titles: string[];
}

export interface PacingInsights {
  avg_tension: number;
  peak: Peak | null;
  climax_position: number | null; // 0..1 through the story
  climax_in_back_third: boolean | null;
  shape: string;
  flat_stretch: FlatStretch | null;
}

export interface TensionAnalysis {
  beats: TensionBeat[];
  insights: PacingInsights;
}

function agentBaseUrl(): string {
  const configured = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "");
  if (configured) return configured;
  if (typeof window !== "undefined" && window.location.hostname.includes("github.dev")) {
    const hostname = window.location.hostname;
    const codespaceDomain = hostname.replace("-3002", "-8000").replace("-3000", "-8000");
    return `https://${codespaceDomain}`;
  }
  return "http://127.0.0.1:8000";
}

export interface TensionAnalysisOptions {
  roomId: string;
  nodes: { id: string; data: Record<string, unknown> }[];
  edges: { id: string; source: string; target: string; data?: Record<string, unknown> }[];
  storyFacts: { category: string; content: string }[];
}

export async function fetchTensionAnalysis(
  opts: TensionAnalysisOptions
): Promise<TensionAnalysis> {
  const res = await fetch(`${agentBaseUrl()}/analytics/tension`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      room_id: opts.roomId,
      nodes: opts.nodes,
      edges: opts.edges,
      story_facts: opts.storyFacts,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(detail || `Tension analysis failed (${res.status})`);
  }

  return res.json();
}

/** Pacing tag → accent color (matches the site's semantic palette). */
export const PACING_COLOR: Record<PacingTag, string> = {
  quiet: "#4FC3F7",
  slow: "#05D582",
  building: "#FFCC00",
  peak: "#FF2A6D",
  falling: "#B388FF",
};

/** Render a TensionAnalysis as Markdown (for copy / download). */
export function tensionToMarkdown(a: TensionAnalysis): string {
  const i = a.insights;
  const lines: string[] = [];
  lines.push("# Pacing & Tension Analysis");
  lines.push("");
  lines.push(`**Average tension:** ${i.avg_tension}/10`);
  lines.push(`**Overall shape:** ${i.shape}`);
  if (i.peak) lines.push(`**Climax candidate:** "${i.peak.title}" (${i.peak.tension}/10)`);
  if (i.climax_position !== null) {
    lines.push(
      `**Climax position:** ${Math.round(i.climax_position * 100)}% through the story` +
        (i.climax_in_back_third === null
          ? ""
          : i.climax_in_back_third
          ? " (good — in the back third)"
          : " (early — consider pushing the peak later)")
    );
  }
  if (i.flat_stretch) {
    lines.push(
      `**Flat stretch:** ${i.flat_stretch.length} beats in a row — ${i.flat_stretch.beat_titles.join(", ")}`
    );
  }
  lines.push("");
  lines.push("## Per-beat tension");
  a.beats.forEach((b, idx) => {
    lines.push(`${idx + 1}. **${b.title}** — ${b.tension}/10 (${b.pacing}): ${b.note}`);
  });
  lines.push("");
  lines.push("---");
  lines.push("_Generated by The Writers' Room · powered by IBM Granite_");
  return lines.join("\n");
}
