/**
 * Coverage report client — generates a professional script-reader's report.
 * The LLM lives in FastAPI (POST /coverage/generate); this wraps it for the UI.
 *
 * Coverage is the industry artifact a studio reader sells for $50–150 per
 * script: logline, premise, verdict (Recommend/Consider/Pass), a 1–10 score,
 * strengths, weaknesses, plot holes, per-character notes, structure, and a
 * marketability read.
 */

export interface CoverageCharacterNote {
  name: string;
  note: string;
}

export type CoverageVerdict = "Recommend" | "Consider" | "Pass";

export interface CoverageReport {
  logline: string;
  premise: string;
  verdict: CoverageVerdict;
  overall_score: number;
  strengths: string[];
  weaknesses: string[];
  plot_holes: string[];
  character_notes: CoverageCharacterNote[];
  structure_note: string;
  marketability: string;
}

function agentBaseUrl(): string {
  const configured = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "");
  if (configured) return configured;
  if (typeof window !== "undefined" && window.location.hostname.includes("github.dev")) {
    const hostname = window.location.hostname;
    const codespaceDomain = hostname.replace("-3002", "-8000").replace("-3000", "-8000");
    return `https://${codespaceDomain}`;
  }
  return "http://127.0.0.1:8000";
}

export interface GenerateCoverageOptions {
  roomId: string;
  nodes: { id: string; data: Record<string, unknown> }[];
  edges: { id: string; source: string; target: string; data?: Record<string, unknown> }[];
  storyFacts: { category: string; content: string }[];
}

export async function generateCoverage(opts: GenerateCoverageOptions): Promise<CoverageReport> {
  const res = await fetch(`${agentBaseUrl()}/coverage/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      room_id: opts.roomId,
      nodes: opts.nodes,
      edges: opts.edges,
      story_facts: opts.storyFacts,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(detail || `Coverage generation failed (${res.status})`);
  }

  return res.json();
}

/** Verdict → accent color (matches the site's semantic palette). */
export const VERDICT_COLOR: Record<CoverageVerdict, string> = {
  Recommend: "#05D582",
  Consider: "#FFCC00",
  Pass: "#FF2A6D",
};

/** Render a CoverageReport as Markdown (for download / copy). */
export function coverageToMarkdown(report: CoverageReport): string {
  const lines: string[] = [];
  lines.push("# Coverage Report");
  lines.push("");
  lines.push(`**Verdict:** ${report.verdict} · **Score:** ${report.overall_score}/10`);
  lines.push("");
  lines.push(`**Logline:** ${report.logline}`);
  lines.push("");
  lines.push("## Premise");
  lines.push(report.premise);
  lines.push("");
  lines.push("## Strengths");
  report.strengths.forEach((s) => lines.push(`- ${s}`));
  lines.push("");
  lines.push("## Weaknesses");
  report.weaknesses.forEach((w) => lines.push(`- ${w}`));
  lines.push("");
  lines.push("## Plot Holes / Continuity");
  if (report.plot_holes.length === 0) {
    lines.push("- None detected.");
  } else {
    report.plot_holes.forEach((p) => lines.push(`- ${p}`));
  }
  lines.push("");
  lines.push("## Character Notes");
  report.character_notes.forEach((c) => {
    lines.push(`### ${c.name}`);
    lines.push(c.note);
    lines.push("");
  });
  lines.push("## Structure");
  lines.push(report.structure_note);
  lines.push("");
  lines.push("## Marketability");
  lines.push(report.marketability);
  lines.push("");
  lines.push("---");
  lines.push("_Generated by The Writers' Room · powered by IBM Granite_");
  return lines.join("\n");
}
