/**
 * Pitch deck client — generates a producer-ready pitch from the story graph.
 * The LLM lives in FastAPI (POST /pitch/generate); this wraps it for the UI.
 */

export interface PitchCharacter {
  name: string;
  role: string;
  bio: string;
}

export interface PitchDeck {
  title: string;
  logline: string;
  synopsis: string;
  genre: string;
  tone: string;
  comparable_titles: string[];
  characters: PitchCharacter[];
  themes: string[];
  hook: string;
}

function agentBaseUrl(): string {
  const configured = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "");
  if (configured) return configured;
  if (typeof window !== "undefined" && window.location.hostname.includes("github.dev")) {
    const hostname = window.location.hostname;
    const codespaceDomain = hostname.replace("-3002", "-8000").replace("-3000", "-8000");
    return `https://${codespaceDomain}`;
  }
  return "http://127.0.0.1:8000";
}

export interface GeneratePitchOptions {
  roomId: string;
  nodes: { id: string; data: Record<string, unknown> }[];
  edges: { id: string; source: string; target: string; data?: Record<string, unknown> }[];
  storyFacts: { category: string; content: string }[];
  notes?: string;
}

export async function generatePitch(opts: GeneratePitchOptions): Promise<PitchDeck> {
  const res = await fetch(`${agentBaseUrl()}/pitch/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      room_id: opts.roomId,
      nodes: opts.nodes,
      edges: opts.edges,
      story_facts: opts.storyFacts,
      notes: opts.notes ?? null,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(detail || `Pitch generation failed (${res.status})`);
  }

  return res.json();
}

/** Render a PitchDeck as Markdown (for download / copy). */
export function pitchToMarkdown(deck: PitchDeck): string {
  const lines: string[] = [];
  lines.push(`# ${deck.title}`);
  lines.push("");
  lines.push(`**Logline:** ${deck.logline}`);
  lines.push("");
  lines.push(`**Genre:** ${deck.genre} · **Tone:** ${deck.tone}`);
  lines.push("");
  lines.push("## Synopsis");
  lines.push(deck.synopsis);
  lines.push("");
  lines.push("## Comparable Titles");
  deck.comparable_titles.forEach((c) => lines.push(`- ${c}`));
  lines.push("");
  lines.push("## Characters");
  deck.characters.forEach((c) => {
    lines.push(`### ${c.name} — ${c.role}`);
    lines.push(c.bio);
    lines.push("");
  });
  lines.push("## Themes");
  deck.themes.forEach((t) => lines.push(`- ${t}`));
  lines.push("");
  lines.push("## The Hook");
  lines.push(deck.hook);
  lines.push("");
  lines.push("---");
  lines.push("_Generated by The Writers' Room · powered by IBM Granite_");
  return lines.join("\n");
}
